# Bankraft 1.2.2.8
# Created by CJ Burkey

GUI Name: '&2Bank'
Max Acc: 5
Account Item: CHEST
Balance Item: GOLD_INGOT
Deposit Item: EMERALD
DepWith Item: DIAMOND
Back Item: BARRIER
BackAccount Item: ARROW
No Item: SIGN
Time Between: 120
Inter Amount: 1.005

Message StartError: '&4There was an error with your economy.  Is Vault installed?'
Message TransFail: '&4Transaction failed!'
Message AccErr: '&4There was an error with your request!'
Message Usage: '&4Usage: /bank [<create/delete/deposit/withdraw> <name> {amount}]'
Message Limit: '&4Account limit reached!'
Message Exist: '&4Account already exists!'
Message StartWorked: '&2Vault found! Everything should work!'
Message Interest: '&2Interest added to all accounts.'
Message TransSucc: '&2Transaction success!'
Message AccCreate: '&2Account created!'
Message AccDel: '&2Account deleted!'